#!/usr/bin/env python3
"""
Patches app/projects/page.tsx (Project Center) to add:
  1. The ability to attach a Reference Document as a URL link, not just an
     uploaded file (Documents tab).
  2. A new "Status Reports" section on the same tab -- PDF upload or URL
     link, each with its own date stamp.

Safe to re-run: every anchor must match EXACTLY ONCE or the whole patch
aborts with no changes written (see apply_one below).

Run from ~/ps-dashboard on the server:
  python3 patch_documents_links_status_reports.py
"""
import sys

PATH = "app/projects/page.tsx"


def apply_one(content, anchor, replacement, label):
    count = content.count(anchor)
    if count != 1:
        print(f"FAIL: anchor not found exactly once for '{label}' (found {count})")
        sys.exit(1)
    return content.replace(anchor, replacement, 1)


def main():
    with open(PATH, "r") as f:
        content = f.read()

    # --- 1. New state for link mode + Status Reports ---
    anchor1 = "  const [uploadingSopDoc, setUploadingSopDoc] = useState(false)\n"
    replacement1 = (
        "  const [uploadingSopDoc, setUploadingSopDoc] = useState(false)\n"
        "  const [sopDocMode, setSopDocMode] = useState<'file' | 'link'>('file')\n"
        "  const [sopDocUrl, setSopDocUrl] = useState('')\n"
        "  // Status Reports section state (PDF upload or URL link, each with a date stamp)\n"
        "  const [addingStatusReport, setAddingStatusReport] = useState(false)\n"
        "  const [statusReportTitle, setStatusReportTitle] = useState('')\n"
        "  const [statusReportMode, setStatusReportMode] = useState<'file' | 'link'>('file')\n"
        "  const [statusReportFile, setStatusReportFile] = useState<File | null>(null)\n"
        "  const [statusReportUrl, setStatusReportUrl] = useState('')\n"
        "  const [statusReportDate, setStatusReportDate] = useState('')\n"
        "  const [uploadingStatusReport, setUploadingStatusReport] = useState(false)\n"
    )
    content = apply_one(content, anchor1, replacement1, "new state")

    # --- 2. statusReports filter, alongside sopDocuments ---
    anchor2 = "  const sopDocuments = data?.documents?.filter((d: any) => d.project_id === selectedProject?.id && d.category === 'SOP') || []\n"
    replacement2 = (
        anchor2
        + "  const statusReports = data?.documents?.filter((d: any) => d.project_id === selectedProject?.id && d.category === 'StatusReport') || []\n"
    )
    content = apply_one(content, anchor2, replacement2, "statusReports filter")

    # --- 3. docIcon: add a link icon ---
    anchor3 = "  const docIcon = (t: string) => t === 'pdf' ? '\U0001F4C4' : (t === 'doc' || t === 'docx') ? '\U0001F4DD' : (t === 'xls' || t === 'xlsx') ? '\U0001F4CA' : (t === 'ppt' || t === 'pptx') ? '\U0001F4C8' : '\U0001F4C1'\n"
    replacement3 = "  const docIcon = (t: string) => t === 'pdf' ? '\U0001F4C4' : (t === 'doc' || t === 'docx') ? '\U0001F4DD' : (t === 'xls' || t === 'xlsx') ? '\U0001F4CA' : (t === 'ppt' || t === 'pptx') ? '\U0001F4C8' : t === 'link' ? '\U0001F517' : '\U0001F4C1'\n"
    content = apply_one(content, anchor3, replacement3, "docIcon link case")

    # --- 4. uploadSopDocument becomes mode-aware; add createStatusReport ---
    anchor4 = (
        "  async function uploadSopDocument() {\n"
        "    if (!sopDocFile) return\n"
        "    setUploadingSopDoc(true)\n"
        "    try {\n"
        "      const formData = new FormData()\n"
        "      formData.append('file', sopDocFile)\n"
        "      formData.append('title', sopDocTitle || sopDocFile.name)\n"
        "      formData.append('category', 'SOP')\n"
        "      formData.append('project_id', selectedProject.id)\n"
        "      const res = await fetch('/api/upload', { method: 'POST', body: formData })\n"
        "      const result = await res.json()\n"
        "      if (result.success) {\n"
        "        await loadProjects()\n"
        "        setAddingSopDoc(false)\n"
        "        setSopDocTitle('')\n"
        "        setSopDocFile(null)\n"
        "      }\n"
        "    } finally {\n"
        "      setUploadingSopDoc(false)\n"
        "    }\n"
        "  }\n"
    )
    replacement4 = (
        "  async function uploadSopDocument() {\n"
        "    if (sopDocMode === 'link') {\n"
        "      if (!sopDocUrl.trim()) return\n"
        "      setUploadingSopDoc(true)\n"
        "      try {\n"
        "        const res = await fetch('/api/documents/link', {\n"
        "          method: 'POST',\n"
        "          headers: { 'Content-Type': 'application/json' },\n"
        "          body: JSON.stringify({\n"
        "            title: sopDocTitle || sopDocUrl,\n"
        "            url: sopDocUrl,\n"
        "            category: 'SOP',\n"
        "            project_id: selectedProject.id,\n"
        "          }),\n"
        "        })\n"
        "        const result = await res.json()\n"
        "        if (result.success) {\n"
        "          await loadProjects()\n"
        "          setAddingSopDoc(false)\n"
        "          setSopDocTitle('')\n"
        "          setSopDocUrl('')\n"
        "          setSopDocMode('file')\n"
        "        }\n"
        "      } finally {\n"
        "        setUploadingSopDoc(false)\n"
        "      }\n"
        "      return\n"
        "    }\n"
        "    if (!sopDocFile) return\n"
        "    setUploadingSopDoc(true)\n"
        "    try {\n"
        "      const formData = new FormData()\n"
        "      formData.append('file', sopDocFile)\n"
        "      formData.append('title', sopDocTitle || sopDocFile.name)\n"
        "      formData.append('category', 'SOP')\n"
        "      formData.append('project_id', selectedProject.id)\n"
        "      const res = await fetch('/api/upload', { method: 'POST', body: formData })\n"
        "      const result = await res.json()\n"
        "      if (result.success) {\n"
        "        await loadProjects()\n"
        "        setAddingSopDoc(false)\n"
        "        setSopDocTitle('')\n"
        "        setSopDocFile(null)\n"
        "      }\n"
        "    } finally {\n"
        "      setUploadingSopDoc(false)\n"
        "    }\n"
        "  }\n"
        "  async function createStatusReport() {\n"
        "    if (statusReportMode === 'link') {\n"
        "      if (!statusReportUrl.trim()) return\n"
        "      setUploadingStatusReport(true)\n"
        "      try {\n"
        "        const res = await fetch('/api/documents/link', {\n"
        "          method: 'POST',\n"
        "          headers: { 'Content-Type': 'application/json' },\n"
        "          body: JSON.stringify({\n"
        "            title: statusReportTitle || statusReportUrl,\n"
        "            url: statusReportUrl,\n"
        "            category: 'StatusReport',\n"
        "            project_id: selectedProject.id,\n"
        "            report_date: statusReportDate || null,\n"
        "          }),\n"
        "        })\n"
        "        const result = await res.json()\n"
        "        if (result.success) {\n"
        "          await loadProjects()\n"
        "          setAddingStatusReport(false)\n"
        "          setStatusReportTitle('')\n"
        "          setStatusReportUrl('')\n"
        "          setStatusReportDate('')\n"
        "          setStatusReportMode('file')\n"
        "        }\n"
        "      } finally {\n"
        "        setUploadingStatusReport(false)\n"
        "      }\n"
        "      return\n"
        "    }\n"
        "    if (!statusReportFile) return\n"
        "    setUploadingStatusReport(true)\n"
        "    try {\n"
        "      const formData = new FormData()\n"
        "      formData.append('file', statusReportFile)\n"
        "      formData.append('title', statusReportTitle || statusReportFile.name)\n"
        "      formData.append('category', 'StatusReport')\n"
        "      formData.append('project_id', selectedProject.id)\n"
        "      if (statusReportDate) formData.append('report_date', statusReportDate)\n"
        "      const res = await fetch('/api/upload', { method: 'POST', body: formData })\n"
        "      const result = await res.json()\n"
        "      if (result.success) {\n"
        "        await loadProjects()\n"
        "        setAddingStatusReport(false)\n"
        "        setStatusReportTitle('')\n"
        "        setStatusReportFile(null)\n"
        "        setStatusReportDate('')\n"
        "      }\n"
        "    } finally {\n"
        "      setUploadingStatusReport(false)\n"
        "    }\n"
        "  }\n"
    )
    content = apply_one(content, anchor4, replacement4, "uploadSopDocument + createStatusReport")

    # --- 5. Reference Documents add-form: mode toggle (file vs link) ---
    anchor5 = (
        "                      {addingSopDoc && (\n"
        "                        <div style={{ background: '#F4F5F6', border: '1px solid #CCCCCC', borderRadius: '6px', padding: '12px', marginBottom: '12px', display: 'grid', gap: '8px' }}>\n"
        "                          <input\n"
        "                            placeholder=\"Document title (optional — defaults to filename)\"\n"
        "                            value={sopDocTitle}\n"
        "                            onChange={e => setSopDocTitle(e.target.value)}\n"
        "                            style={{ fontSize: '12px', padding: '6px 8px', border: '1px solid #CCCCCC', borderRadius: '5px' }}\n"
        "                          />\n"
        "                          <input\n"
        "                            type=\"file\"\n"
        "                            onChange={e => setSopDocFile(e.target.files?.[0] || null)}\n"
        "                            style={{ fontSize: '12px' }}\n"
        "                          />\n"
        "                          <div style={{ display: 'flex', gap: '6px' }}>\n"
        "                            <button\n"
        "                              onClick={uploadSopDocument}\n"
        "                              disabled={!sopDocFile || uploadingSopDoc}\n"
        "                              style={{ padding: '7px 14px', background: (!sopDocFile || uploadingSopDoc) ? '#C9CFD4' : '#A50021', color: '#fff', border: 'none', borderRadius: '5px', fontSize: '12px', fontWeight: 700, cursor: (!sopDocFile || uploadingSopDoc) ? 'default' : 'pointer', fontFamily: 'Oswald, sans-serif' }}\n"
        "                            >\n"
        "                              {uploadingSopDoc ? 'Uploading...' : 'Upload'}\n"
        "                            </button>\n"
        "                            <button\n"
        "                              onClick={() => { setAddingSopDoc(false); setSopDocTitle(''); setSopDocFile(null) }}\n"
        "                              style={{ padding: '7px 14px', background: '#fff', color: '#323E48', border: '1px solid #CCCCCC', borderRadius: '5px', fontSize: '12px', fontWeight: 600, cursor: 'pointer' }}\n"
        "                            >\n"
        "                              Cancel\n"
        "                            </button>\n"
        "                          </div>\n"
        "                        </div>\n"
        "                      )}\n"
    )
    replacement5 = (
        "                      {addingSopDoc && (\n"
        "                        <div style={{ background: '#F4F5F6', border: '1px solid #CCCCCC', borderRadius: '6px', padding: '12px', marginBottom: '12px', display: 'grid', gap: '8px' }}>\n"
        "                          <div style={{ display: 'flex', gap: '6px' }}>\n"
        "                            <button\n"
        "                              onClick={() => setSopDocMode('file')}\n"
        "                              style={{ padding: '5px 10px', background: sopDocMode === 'file' ? '#323E48' : '#fff', color: sopDocMode === 'file' ? '#fff' : '#323E48', border: '1px solid #CCCCCC', borderRadius: '4px', fontSize: '11px', fontWeight: 700, cursor: 'pointer' }}\n"
        "                            >\n"
        "                              Upload File\n"
        "                            </button>\n"
        "                            <button\n"
        "                              onClick={() => setSopDocMode('link')}\n"
        "                              style={{ padding: '5px 10px', background: sopDocMode === 'link' ? '#323E48' : '#fff', color: sopDocMode === 'link' ? '#fff' : '#323E48', border: '1px solid #CCCCCC', borderRadius: '4px', fontSize: '11px', fontWeight: 700, cursor: 'pointer' }}\n"
        "                            >\n"
        "                              Add Link\n"
        "                            </button>\n"
        "                          </div>\n"
        "                          <input\n"
        "                            placeholder=\"Document title (optional — defaults to filename)\"\n"
        "                            value={sopDocTitle}\n"
        "                            onChange={e => setSopDocTitle(e.target.value)}\n"
        "                            style={{ fontSize: '12px', padding: '6px 8px', border: '1px solid #CCCCCC', borderRadius: '5px' }}\n"
        "                          />\n"
        "                          {sopDocMode === 'file' ? (\n"
        "                            <input\n"
        "                              type=\"file\"\n"
        "                              onChange={e => setSopDocFile(e.target.files?.[0] || null)}\n"
        "                              style={{ fontSize: '12px' }}\n"
        "                            />\n"
        "                          ) : (\n"
        "                            <input\n"
        "                              placeholder=\"https://...\"\n"
        "                              value={sopDocUrl}\n"
        "                              onChange={e => setSopDocUrl(e.target.value)}\n"
        "                              style={{ fontSize: '12px', padding: '6px 8px', border: '1px solid #CCCCCC', borderRadius: '5px' }}\n"
        "                            />\n"
        "                          )}\n"
        "                          <div style={{ display: 'flex', gap: '6px' }}>\n"
        "                            <button\n"
        "                              onClick={uploadSopDocument}\n"
        "                              disabled={(sopDocMode === 'file' ? !sopDocFile : !sopDocUrl.trim()) || uploadingSopDoc}\n"
        "                              style={{ padding: '7px 14px', background: ((sopDocMode === 'file' ? !sopDocFile : !sopDocUrl.trim()) || uploadingSopDoc) ? '#C9CFD4' : '#A50021', color: '#fff', border: 'none', borderRadius: '5px', fontSize: '12px', fontWeight: 700, cursor: ((sopDocMode === 'file' ? !sopDocFile : !sopDocUrl.trim()) || uploadingSopDoc) ? 'default' : 'pointer', fontFamily: 'Oswald, sans-serif' }}\n"
        "                            >\n"
        "                              {uploadingSopDoc ? (sopDocMode === 'file' ? 'Uploading...' : 'Saving...') : (sopDocMode === 'file' ? 'Upload' : 'Save Link')}\n"
        "                            </button>\n"
        "                            <button\n"
        "                              onClick={() => { setAddingSopDoc(false); setSopDocTitle(''); setSopDocFile(null); setSopDocUrl(''); setSopDocMode('file') }}\n"
        "                              style={{ padding: '7px 14px', background: '#fff', color: '#323E48', border: '1px solid #CCCCCC', borderRadius: '5px', fontSize: '12px', fontWeight: 600, cursor: 'pointer' }}\n"
        "                            >\n"
        "                              Cancel\n"
        "                            </button>\n"
        "                          </div>\n"
        "                        </div>\n"
        "                      )}\n"
    )
    content = apply_one(content, anchor5, replacement5, "Reference Documents add-form mode toggle")

    # --- 6. Reference Documents list row: link vs download ---
    anchor6 = (
        "                          <a\n"
        "                            href={`/api/documents/download?file=${encodeURIComponent(String(d.file_url).split('/').pop() || '')}`}\n"
        "                            style={{ padding: '6px 12px', background: '#00538C', color: '#fff', borderRadius: '4px', fontSize: '11px', fontWeight: 700, textDecoration: 'none', flexShrink: 0 }}\n"
        "                          >\n"
        "                            Download\n"
        "                          </a>\n"
        "                          {isAdmin && (\n"
        "                            <button\n"
        "                              onClick={() => deleteSopDocument(d.id)}\n"
    )
    replacement6 = (
        "                          {d.file_type === 'link' ? (\n"
        "                            <a\n"
        "                              href={d.url}\n"
        "                              target=\"_blank\"\n"
        "                              rel=\"noopener noreferrer\"\n"
        "                              style={{ padding: '6px 12px', background: '#00538C', color: '#fff', borderRadius: '4px', fontSize: '11px', fontWeight: 700, textDecoration: 'none', flexShrink: 0 }}\n"
        "                            >\n"
        "                              Open Link\n"
        "                            </a>\n"
        "                          ) : (\n"
        "                            <a\n"
        "                              href={`/api/documents/download?file=${encodeURIComponent(String(d.file_url).split('/').pop() || '')}`}\n"
        "                              style={{ padding: '6px 12px', background: '#00538C', color: '#fff', borderRadius: '4px', fontSize: '11px', fontWeight: 700, textDecoration: 'none', flexShrink: 0 }}\n"
        "                            >\n"
        "                              Download\n"
        "                            </a>\n"
        "                          )}\n"
        "                          {isAdmin && (\n"
        "                            <button\n"
        "                              onClick={() => deleteSopDocument(d.id)}\n"
    )
    content = apply_one(content, anchor6, replacement6, "Reference Documents link-aware row")

    # --- 7. Insert the new Status Reports section after Reference Documents ---
    anchor7 = (
        "                          )}\n"
        "                        </div>\n"
        "                      ))}\n"
        "                    </div>\n"
        "                  </div>\n"
        "                )}\n"
        "                {/* CUSTOMER CONTACTS */}\n"
    )
    status_reports_section = (
        "                    {/* Status Reports */}\n"
        "                    <div style={{ marginTop: '24px', paddingTop: '20px', borderTop: '1px solid #EAECEE' }}>\n"
        "                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>\n"
        "                        <h3 style={{ fontFamily: 'Oswald, sans-serif', fontSize: '12px', textTransform: 'uppercase', letterSpacing: '.5px', color: '#A50021', margin: 0 }}>\n"
        "                          Status Reports\n"
        "                        </h3>\n"
        "                        {isAdmin && !addingStatusReport && (\n"
        "                          <button\n"
        "                            onClick={() => setAddingStatusReport(true)}\n"
        "                            style={{ background: 'none', border: '1px solid #CCCCCC', color: '#323E48', borderRadius: '4px', fontSize: '11px', fontWeight: 700, cursor: 'pointer', padding: '4px 10px' }}\n"
        "                          >\n"
        "                            + Add Status Report\n"
        "                          </button>\n"
        "                        )}\n"
        "                      </div>\n"
        "                      {addingStatusReport && (\n"
        "                        <div style={{ background: '#F4F5F6', border: '1px solid #CCCCCC', borderRadius: '6px', padding: '12px', marginBottom: '12px', display: 'grid', gap: '8px' }}>\n"
        "                          <div style={{ display: 'flex', gap: '6px' }}>\n"
        "                            <button\n"
        "                              onClick={() => setStatusReportMode('file')}\n"
        "                              style={{ padding: '5px 10px', background: statusReportMode === 'file' ? '#323E48' : '#fff', color: statusReportMode === 'file' ? '#fff' : '#323E48', border: '1px solid #CCCCCC', borderRadius: '4px', fontSize: '11px', fontWeight: 700, cursor: 'pointer' }}\n"
        "                            >\n"
        "                              Upload PDF\n"
        "                            </button>\n"
        "                            <button\n"
        "                              onClick={() => setStatusReportMode('link')}\n"
        "                              style={{ padding: '5px 10px', background: statusReportMode === 'link' ? '#323E48' : '#fff', color: statusReportMode === 'link' ? '#fff' : '#323E48', border: '1px solid #CCCCCC', borderRadius: '4px', fontSize: '11px', fontWeight: 700, cursor: 'pointer' }}\n"
        "                            >\n"
        "                              Add Link\n"
        "                            </button>\n"
        "                          </div>\n"
        "                          <input\n"
        "                            placeholder=\"Report title (optional — defaults to filename)\"\n"
        "                            value={statusReportTitle}\n"
        "                            onChange={e => setStatusReportTitle(e.target.value)}\n"
        "                            style={{ fontSize: '12px', padding: '6px 8px', border: '1px solid #CCCCCC', borderRadius: '5px' }}\n"
        "                          />\n"
        "                          <input\n"
        "                            type=\"date\"\n"
        "                            value={statusReportDate}\n"
        "                            onChange={e => setStatusReportDate(e.target.value)}\n"
        "                            style={{ fontSize: '12px', padding: '6px 8px', border: '1px solid #CCCCCC', borderRadius: '5px' }}\n"
        "                          />\n"
        "                          {statusReportMode === 'file' ? (\n"
        "                            <input\n"
        "                              type=\"file\"\n"
        "                              accept=\"application/pdf\"\n"
        "                              onChange={e => setStatusReportFile(e.target.files?.[0] || null)}\n"
        "                              style={{ fontSize: '12px' }}\n"
        "                            />\n"
        "                          ) : (\n"
        "                            <input\n"
        "                              placeholder=\"https://...\"\n"
        "                              value={statusReportUrl}\n"
        "                              onChange={e => setStatusReportUrl(e.target.value)}\n"
        "                              style={{ fontSize: '12px', padding: '6px 8px', border: '1px solid #CCCCCC', borderRadius: '5px' }}\n"
        "                            />\n"
        "                          )}\n"
        "                          <div style={{ display: 'flex', gap: '6px' }}>\n"
        "                            <button\n"
        "                              onClick={createStatusReport}\n"
        "                              disabled={(statusReportMode === 'file' ? !statusReportFile : !statusReportUrl.trim()) || uploadingStatusReport}\n"
        "                              style={{ padding: '7px 14px', background: ((statusReportMode === 'file' ? !statusReportFile : !statusReportUrl.trim()) || uploadingStatusReport) ? '#C9CFD4' : '#A50021', color: '#fff', border: 'none', borderRadius: '5px', fontSize: '12px', fontWeight: 700, cursor: ((statusReportMode === 'file' ? !statusReportFile : !statusReportUrl.trim()) || uploadingStatusReport) ? 'default' : 'pointer', fontFamily: 'Oswald, sans-serif' }}\n"
        "                            >\n"
        "                              {uploadingStatusReport ? (statusReportMode === 'file' ? 'Uploading...' : 'Saving...') : (statusReportMode === 'file' ? 'Upload' : 'Save Link')}\n"
        "                            </button>\n"
        "                            <button\n"
        "                              onClick={() => { setAddingStatusReport(false); setStatusReportTitle(''); setStatusReportFile(null); setStatusReportUrl(''); setStatusReportDate(''); setStatusReportMode('file') }}\n"
        "                              style={{ padding: '7px 14px', background: '#fff', color: '#323E48', border: '1px solid #CCCCCC', borderRadius: '5px', fontSize: '12px', fontWeight: 600, cursor: 'pointer' }}\n"
        "                            >\n"
        "                              Cancel\n"
        "                            </button>\n"
        "                          </div>\n"
        "                        </div>\n"
        "                      )}\n"
        "                      {statusReports.length === 0 ? (\n"
        "                        <p style={{ fontSize: '12px', color: '#8a9199', textAlign: 'center', padding: '16px' }}>\n"
        "                          No status reports uploaded yet.\n"
        "                        </p>\n"
        "                      ) : statusReports\n"
        "                          .slice()\n"
        "                          .sort((a: any, b: any) => {\n"
        "                            const ad = a.report_date ? new Date(a.report_date).getTime() : 0\n"
        "                            const bd = b.report_date ? new Date(b.report_date).getTime() : 0\n"
        "                            if (ad !== bd) return bd - ad\n"
        "                            return new Date(b.created_at).getTime() - new Date(a.created_at).getTime()\n"
        "                          })\n"
        "                          .map((d: any) => (\n"
        "                        <div key={d.id} style={{ display: 'flex', alignItems: 'center', gap: '10px', padding: '10px 0', borderBottom: '1px solid #EAECEE' }}>\n"
        "                          <span style={{ fontSize: '20px', flexShrink: 0 }}>{docIcon(d.file_type)}</span>\n"
        "                          <div style={{ flex: 1, minWidth: 0 }}>\n"
        "                            <p style={{ fontSize: '12px', fontWeight: 600, color: '#323E48' }}>{d.title}</p>\n"
        "                            <p style={{ fontSize: '10px', color: '#8a9199' }}>\n"
        "                              {d.report_date\n"
        "                                ? `Report date ${new Date(d.report_date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })} · `\n"
        "                                : ''}\n"
        "                              Uploaded by {d.uploaded_by} · {new Date(d.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}\n"
        "                            </p>\n"
        "                          </div>\n"
        "                          {d.file_type === 'link' ? (\n"
        "                            <a\n"
        "                              href={d.url}\n"
        "                              target=\"_blank\"\n"
        "                              rel=\"noopener noreferrer\"\n"
        "                              style={{ padding: '6px 12px', background: '#00538C', color: '#fff', borderRadius: '4px', fontSize: '11px', fontWeight: 700, textDecoration: 'none', flexShrink: 0 }}\n"
        "                            >\n"
        "                              Open Link\n"
        "                            </a>\n"
        "                          ) : (\n"
        "                            <a\n"
        "                              href={`/api/documents/download?file=${encodeURIComponent(String(d.file_url).split('/').pop() || '')}`}\n"
        "                              style={{ padding: '6px 12px', background: '#00538C', color: '#fff', borderRadius: '4px', fontSize: '11px', fontWeight: 700, textDecoration: 'none', flexShrink: 0 }}\n"
        "                            >\n"
        "                              Download\n"
        "                            </a>\n"
        "                          )}\n"
        "                          {isAdmin && (\n"
        "                            <button\n"
        "                              onClick={() => deleteSopDocument(d.id)}\n"
        "                              style={{ padding: '6px 10px', background: '#fff', color: '#A50021', border: '1px solid #CCCCCC', borderRadius: '4px', fontSize: '11px', cursor: 'pointer', flexShrink: 0 }}\n"
        "                            >\n"
        "                              Delete\n"
        "                            </button>\n"
        "                          )}\n"
        "                        </div>\n"
        "                      ))}\n"
        "                    </div>\n"
    )
    replacement7 = (
        "                          )}\n"
        "                        </div>\n"
        "                      ))}\n"
        "                    </div>\n"
        + status_reports_section
        + "                  </div>\n"
        "                )}\n"
        "                {/* CUSTOMER CONTACTS */}\n"
    )
    content = apply_one(content, anchor7, replacement7, "insert Status Reports section")

    with open(PATH, "w") as f:
        f.write(content)

    print("All 7 patches applied successfully.")


if __name__ == "__main__":
    main()
